### ISSUE TITLE
MOTIS crashes using the current Transitous dataset

### ISSUE THREAD

**Issue by jbruechert** [motis-project/motis#554]
**Backtrace**:
```C++
#0  geo::operator== (lhs=..., rhs=<synthetic pointer>...) at /var/home/jonah/kde/src/motis/deps/geo/include/geo/latlng.h:23
#1  operator() (__closure=<synthetic pointer>, pos=..., force_if_unchanged=false)
    at /var/home/jonah/kde/src/motis/deps/nigiri/src/rt/frun.cc:404
#2  operator() (__closure=<optimized out>, shape=...) at /var/home/jonah/kde/src/motis/deps/nigiri/src/rt/frun.cc:428
#3  std::__invoke_impl<void, utl::overloaded<nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(std::span<const geo::latlng, 18446744073709551615>)>, nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(nigiri::interval<short unsigned int>)> >, std::span<const geo::latlng, 18446744073709551615> > (__f=...) at /usr/include/c++/14/bits/invoke.h:61
#4  std::__invoke<utl::overloaded<nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(std::span<const geo::latlng, 18446744073709551615>)>, nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(nigiri::interval<short unsigned int>)> >, std::span<const geo::latlng, 18446744073709551615> >
    (__fn=...) at /usr/include/c++/14/bits/invoke.h:96
#5  std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<void> (*)(utl::overloaded<nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(std::span<const geo::latlng, 18446744073709551615>)>, nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(nigiri::interval<short unsigned int>)> >&&, std::variant<std::span<const geo::latlng, 18446744073709551615>, nigiri::interval<short unsigned int> >&&)>, std::integer_sequence<long unsigned int, 0> >::__visit_invoke (__visitor=..., 
    __vars#0=...) at /usr/include/c++/14/variant:1060
#6  std::__do_visit<std::__detail::__variant::__deduce_visit_result<void>, utl::overloaded<nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(std::span<const geo::latlng, 18446744073709551615>)>, nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(nigiri::interval<short unsigned int>)> >, std::variant<std::span<const geo::latlng, 18446744073709551615>, nigiri::interval<short unsigned int> > > (__visitor=...)
    at /usr/include/c++/14/variant:1819
#7  std::visit<utl::overloaded<nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsig--Type <RET> for more, q to quit, c to continue without paging--
ned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(std::span<const geo::latlng, 18446744073709551615>)>, nigiri::rt::frun::for_each_shape_point(const nigiri::shapes_storage*, const nigiri::interval<short unsigned int>&, const std::function<void(const geo::latlng&)>&) const::<lambda(nigiri::interval<short unsigned int>)> >, std::variant<std::span<const geo::latlng, 18446744073709551615>, nigiri::interval<short unsigned int> > > (__visitor=...) at /usr/include/c++/14/variant:1882
#8  nigiri::rt::frun::for_each_shape_point (this=this@entry=0x7f11f01008e0, shapes_data=0x9168580, range=..., callback=...)
    at /var/home/jonah/kde/src/motis/deps/nigiri/src/rt/frun.cc:426
#9  0x00000000009bae38 in motis::nigiri::railviz::impl::create_response(std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&) const::{lambda(motis::nigiri::stop_pair const&)#1}::operator()(motis::nigiri::stop_pair const&) const (
    __closure=__closure@entry=0x7f11f01009d0, r=...) at /var/home/jonah/kde/src/motis/modules/nigiri/src/railviz.cc:299
#10 0x00000000009bbb32 in std::transform<__gnu_cxx::__normal_iterator<motis::nigiri::stop_pair const*, std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > >, std::back_insert_iterator<std::vector<flatbuffers::Offset<motis::railviz::Train>, std::allocator<flatbuffers::Offset<motis::railviz::Train> > > >, motis::nigiri::railviz::impl::create_response(std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&) const::{lambda(motis::nigiri::stop_pair const&)#1}>(__gnu_cxx::__normal_iterator<motis::nigiri::stop_pair const*, std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > >, __gnu_cxx::__normal_iterator<motis::nigiri::stop_pair const*, std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > >, std::back_insert_iterator<std::vector<flatbuffers::Offset<motis::railviz::Train>, std::allocator<flatbuffers::Offset<motis::railviz::Train> > > >, motis::nigiri::railviz::impl::create_response(std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&) const::{lambda(motis::nigiri::stop_pair const&)#1}) (__first=..., __last=..., __result=..., __unary_op=...)
    at /usr/include/c++/14/bits/stl_algo.h:4219
#11 utl::to_vec<std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&, motis::nigiri::railviz::impl::create_response(std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&) const::{lambda(motis::nigiri::stop_pair const&)#1}>(std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&, motis::nigiri::railviz::impl::create_response(std::vector<motis::nigiri::stop_pair, std::allocator<motis::nigiri::stop_pair> > const&) const::{lambda(motis::nigiri::stop_pair const&)#1}&&) (c=std::vector of length 3126, capacity 4096 = {...}, op=...)
    at /var/home/jonah/kde/src/motis/deps/utl/include/utl/to_vec.h:42
#12 0x00000000009bbfeb in motis::nigiri::railviz::impl::create_response (this=this@entry=0x15d203e0, 
    runs=std::vector of length 3126, capacity 4096 = {...}) at /var/home/jonah/kde/src/motis/modules/nigiri/src/railviz.cc:323
#13 0x00000000009be5f4 in motis::nigiri::railviz::impl::get_trains (this=this@entry=0x15d203e0, time_interval=..., area=..., 
--Type <RET> for more, q to quit, c to continue without paging--
    zoom_level=<optimized out>) at /var/home/jonah/kde/src/motis/modules/nigiri/src/railviz.cc:259
#14 0x00000000009be806 in motis::nigiri::railviz::impl::get_trains (this=0x15d203e0, msg=...)
    at /var/home/jonah/kde/src/motis/modules/nigiri/src/railviz.cc:231
#15 0x00000000009b5dfc in motis::nigiri::railviz::get_trains (this=<optimized out>, msg=...)
    at /var/home/jonah/kde/src/motis/modules/nigiri/src/railviz.cc:432
#16 0x000000000098eb5a in operator() (__closure=<optimized out>, msg=...)
    at /var/home/jonah/kde/src/motis/modules/nigiri/src/nigiri.cc:321
#17 std::__invoke_impl<std::shared_ptr<motis::module::message>, motis::nigiri::nigiri::init(motis::module::registry&)::<lambda(const motis::module::msg_ptr&)>&, const std::shared_ptr<motis::module::message>&> (__f=...) at /usr/include/c++/14/bits/invoke.h:61
#18 std::__invoke_r<std::shared_ptr<motis::module::message>, motis::nigiri::nigiri::init(motis::module::registry&)::<lambda(const motis::module::msg_ptr&)>&, const std::shared_ptr<motis::module::message>&> (__fn=...) at /usr/include/c++/14/bits/invoke.h:116
#19 std::_Function_handler<std::shared_ptr<motis::module::message>(const std::shared_ptr<motis::module::message>&), motis::nigiri::nigiri::init(motis::module::registry&)::<lambda(const motis::module::msg_ptr&)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<motis::module::message> &) (__functor=..., __args#0=...) at /usr/include/c++/14/bits/std_function.h:291
#20 0x00000000011236c8 in std::function<std::shared_ptr<motis::module::message>(std::shared_ptr<motis::module::message> const&)>::operator() (this=<optimized out>, __args#0=...) at /usr/include/c++/14/bits/std_function.h:591
#21 operator() (__closure=<optimized out>, m=...) at /var/home/jonah/kde/src/motis/base/module/src/registry.cc:17
#22 std::__invoke_impl<std::shared_ptr<motis::module::message>, motis::module::registry::register_op(const std::string&, motis::module::op_fn_t, ctx::accesses_t&&)::<lambda(const motis::module::msg_ptr&)>&, const std::shared_ptr<motis::module::message>&> (__f=...)
    at /usr/include/c++/14/bits/invoke.h:61
#23 std::__invoke_r<std::shared_ptr<motis::module::message>, motis::module::registry::register_op(const std::string&, motis::module::op_fn_t, ctx::accesses_t&&)::<lambda(const motis::module::msg_ptr&)>&, const std::shared_ptr<motis::module::message>&> (__fn=...)
    at /usr/include/c++/14/bits/invoke.h:116
#24 std::_Function_handler<std::shared_ptr<motis::module::message>(const std::shared_ptr<motis::module::message>&), motis::module::registry::register_op(const std::string&, motis::module::op_fn_t, ctx::accesses_t&&)::<lambda(const motis::module::msg_ptr&)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<motis::module::message> &) (__functor=..., __args#0=...)
    at /usr/include/c++/14/bits/std_function.h:291
--Type <RET> for more, q to quit, c to continue without paging--
tor() (this=0x7f11f0100eb0, __args#0=std::shared_ptr<motis::module::message> (use count 1, weak count 0) = {...}) at /usr/include/c++/14/bits/std_function.h:591
#26 operator() (__closure=0x92cedc0) at /var/home/jonah/kde/src/motis/base/module/src/dispatcher.cc:136
#27 0x0000000000517762 in std::function<void()>::operator() (this=<optimized out>) at /usr/include/c++/14/bits/std_function.h:591
#28 ctx::operation<motis::module::ctx_data>::start (this=<optimized out>) at /var/home/jonah/kde/src/motis/deps/ctx/include/ctx/impl/operation.h:148
#29 ctx::execute<motis::module::ctx_data> (t=...) at /var/home/jonah/kde/src/motis/deps/ctx/include/ctx/operation.h:84
#30 0x00000000011ebf4f in make_fcontext () at make_x86_64_sysv_elf_gas.S:71
#31 0x0000000000000000 in ?? ()

```

**Data for reproducing**: https://github.com/public-transport/transitous/wiki/Using-Transitous-data

when zooming out so that the parts of Europe surrounding Germany are visible, MOTIS crashes.

**Comment by jbruechert** [comment]
Looks like one of the arguments has a dangling reference
```
(gdb) info args
lhs = <error reading variable: Cannot access memory at address 0x7f0dd998e000>
rhs = <synthetic pointer>: {lat_ = 0, lng_ = 0}
```

**Comment by felixguendling** [comment]
Might be connected to
https://github.com/motis-project/nigiri/issues/143

At least this one triggers first in Debug mode.
So maybe fixing that will also fix this problem.
I'll dig deeper later.
