### ISSUE TITLE
asan / ubsan issues

### ISSUE THREAD

**Issue by jbruechert** [motis-project/motis#559]
- [ ] `modules/nigiri/src/guesser.cc:97`
```C++
==511178==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f24e84017f8 at pc 0x000003bee893 bp 0x7fff2a2bfd50 sp 0x7fff2a2bfd48
READ of size 4 at 0x7f24e84017f8 thread T0
    #0 0x3bee892 in get_candidates /home/jonah/kde/src/motis/modules/nigiri/src/guesser.cc:97
    #1 0x3bf083a in motis::nigiri::guesser::guesser(motis::nigiri::tag_lookup const&, nigiri::timetable const&) /home/jonah/kde/src/motis/modules/nigiri/src/guesser.cc:139
    #2 0x3891140 in std::__detail::_MakeUniq<motis::nigiri::guesser>::__single_object std::make_unique<motis::nigiri::guesser, motis::nigiri::tag_lookup&, nigiri::timetable&>(motis::nigiri::tag_lookup&, nigiri::timetable&) /usr/include/c++/14/bits/unique_ptr.h:1076
    #3 0x3891140 in operator() /home/jonah/kde/src/motis/modules/nigiri/src/nigiri.cc:686
    #4 0x7e4745e in std::function<void (std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<motis::module::message>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<motis::module::message> > > > const&, std::function<void (std::shared_ptr<motis::module::message>)> const&)>::operator()(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<motis::module::message>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<motis::module::message> > > > const&, std::function<void (std::shared_ptr<motis::module::message>)> const&) const /usr/include/c++/14/bits/std_function.h:591
    #5 0x7e4745e in operator() /home/jonah/kde/src/motis/base/module/src/event_collector.cc:80
    #6 0x7e4a8c1 in __invoke_impl<std::shared_ptr<motis::module::message>, motis::module::event_collector::require(const std::string&, std::function<bool(std::shared_ptr<motis::module::message>)>)::<lambda(const motis::module::msg_ptr&)>&, std::shared_ptr<motis::module::message> > /usr/include/c++/14/bits/invoke.h:61
    #7 0x7e4a8c1 in __invoke_r<void, motis::module::event_collector::require(const std::string&, std::function<bool(std::shared_ptr<motis::module::message>)>)::<lambda(const motis::module::msg_ptr&)>&, std::shared_ptr<motis::module::message> > /usr/include/c++/14/bits/invoke.h:111
    #8 0x7e4a8c1 in _M_invoke /usr/include/c++/14/bits/std_function.h:290
    #9 0xad03a6 in std::function<void (std::shared_ptr<motis::module::message>)>::operator()(std::shared_ptr<motis::module::message>) const /usr/include/c++/14/bits/std_function.h:591
    #10 0xad03a6 in motis::module::import_dispatcher::run() /home/jonah/kde/src/motis/base/module/include/motis/module/import_dispatcher.h:22
    #11 0xaadd38 in motis::bootstrap::motis_instance::import(motis::bootstrap::module_settings const&, motis::bootstrap::import_settings const&, bool) /home/jonah/kde/src/motis/base/bootstrap/src/motis_instance.cc:98
    #12 0x5774b9 in main /home/jonah/kde/src/motis/base/launcher/src/main.cc:168
    #13 0x7f2a570121c7 in __libc_start_call_main (/lib64/libc.so.6+0x41c7) (BuildId: 9c36f77df28d1669a4f90a66c6da3fe355a08add)
    #14 0x7f2a5701228a in __libc_start_main_impl (/lib64/libc.so.6+0x428a) (BuildId: 9c36f77df28d1669a4f90a66c6da3fe355a08add)
    #15 0x5faaa4 in _start (/var/home/jonah/kde/src/motis/build-debug/motis+0x5faaa4) (BuildId: 7459ebc04b7a0e91445128ce28c78a2400a75ab5)

0x7f24e84017f8 is located 8 bytes before 63902160-byte region [0x7f24e8401800,0x7f24ec0f29d0)
allocated by thread T0 here:
    #0 0x7f2a57ec33f8 in operator new(unsigned long) (/lib64/libasan.so.8+0xc33f8) (BuildId: 54a634d4dcfd86e653fe18078de4c96f231df68e)
    #1 0x3c034ef in std::__new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> >::allocate(unsigned long, void const*) /usr/include/c++/14/bits/new_allocator.h:151
    #2 0x3c034ef in std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> >::allocate(unsigned long) /usr/include/c++/14/bits/allocator.h:196
    #3 0x3c034ef in std::allocator_traits<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > >::allocate(std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> >&, unsigned long) /usr/include/c++/14/bits/alloc_traits.h:478
    #4 0x3c034ef in std::_Vector_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > >::_M_allocate(unsigned long) /usr/include/c++/14/bits/stl_vector.h:380
    #5 0x3c034ef in std::_Vector_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > >::_M_allocate(unsigned long) /usr/include/c++/14/bits/stl_vector.h:377
    #6 0x3c034ef in std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > >::_M_fill_insert(__gnu_cxx::__normal_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>*, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > > >, unsigned long, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> const&) /usr/include/c++/14/bits/vector.tcc:758
    #7 0x3be9587 in std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> > >::resize(unsigned long, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float> const&) /usr/include/c++/14/bits/stl_vector.h:1037
    #8 0x3be9587 in get_candidates /home/jonah/kde/src/motis/modules/nigiri/src/guesser.cc:56
    #9 0x3bf083a in motis::nigiri::guesser::guesser(motis::nigiri::tag_lookup const&, nigiri::timetable const&) /home/jonah/kde/src/motis/modules/nigiri/src/guesser.cc:139

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/jonah/kde/src/motis/modules/nigiri/src/guesser.cc:97 in get_candidates
Shadow bytes around the buggy address:
  0x7f24e8401500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f24e8401580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f24e8401600: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f24e8401680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x7f24e8401700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x7f24e8401780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x7f24e8401800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f24e8401880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f24e8401900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f24e8401980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f24e8401a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==511178==ABORTING

```

**Comment by felixguendling** [comment]
Already fixed in MOTIS 2:
https://github.com/motis-project/icc/commit/b82c757bc587165c66061f2b8a8996a2b572961a#diff-af0e1fe35b010d790a798ea320e76ee10d5065c6f6a5eddeb5dd4d7028406947

I currently don't have capacities to backport and I hope, MOTIS 2 will soon be complete enough to replace MOTIS 0. Currently experimenting with deck.gl to replace railviz.
