### ISSUE TITLE
Crash in import (Arithmetic Exception)

### ISSUE THREAD

**Issue by jbruechert** [motis-project/motis#671]
Backtrace:
```#0  0x0000000000b35c09 in void nigiri::loader::gtfs::expand_frequencies<nigiri::loader::gtfs::expand_trip<nigiri::loader::gtfs::load_timetable(nigiri::loader::loader_config const&, cista::strong<unsigned short, nigiri::_source_idx>, nigiri::loader::dir const&, nigiri::timetable&, serializable_table<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx>, cista::hash_all, cista::equals_all, cista::basic_vector<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr, false, unsigned int, cista::allocator<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr> >, ankerl::unordered_dense::v4_1_0::bucket_type::standard, false>&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::{lambda(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*)#1}::operator()(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*) const::{lambda(nigiri::loader::gtfs::utc_trip&&)#1}>(nigiri::loader::gtfs::trip_data&, cista::basic_vector<std::optional<std::array<std::chrono::duration<short, std::ratio<60l, 1l> >, 512ul> >, cista::raw::ptr, false, cista::strong<unsigned short, nigiri::_timezone_idx>, cista::allocator<std::optional<std::array<std::chrono::duration<short, std::ratio<60l, 1l> >, 512ul> >, cista::raw::ptr> > const&, nigiri::timetable const&, std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*, nigiri::interval<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400l, 1l> > > > const&, nigiri::loader::assistance_times*, nigiri::loader::gtfs::load_timetable(nigiri::loader::loader_config const&, cista::strong<unsigned short, nigiri::_source_idx>, nigiri::loader::dir const&, nigiri::timetable&, serializable_table<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx>, cista::hash_all, cista::equals_all, cista::basic_vector<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr, false, unsigned int, cista::allocator<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr> >, ankerl::unordered_dense::v4_1_0::bucket_type::standard, false>&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::{lambda(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*)#1}::operator()(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*) const::{lambda(nigiri::loader::gtfs::utc_trip&&)#1}&&)::{lambda(nigiri::loader::gtfs::frequency_expanded_trip&&)#1}>(nigiri::loader::gtfs::trip_data const&, std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*, nigiri::loader::gtfs::load_timetable(nigiri::loader::loader_config const&, cista::strong<unsigned short, nigiri::_source_idx>, nigiri::loader::dir const&, nigiri::timetable&, serializable_table<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx>, cista::hash_all, cista::equals_all, cista::basic_vector<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr, false, unsigned int, cista::allocator<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr> >, ankerl::unordered_dense::v4_1_0::bucket_type::standard, false>&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::{lambda(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*)#1}::operator()(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*) const::{lambda(nigiri::loader::gtfs::utc_trip&&)#1}&&) ()
#1  0x0000000000b3692f in nigiri::loader::gtfs::load_timetable(nigiri::loader::loader_config const&, cista::strong<unsigned short, nigiri::_source_idx>, nigiri::loader::dir const&, nigiri::timetable&, serializable_table<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx>, cista::hash_all, cista::equals_all, cista::basic_vector<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr, false, unsigned int, cista::allocator<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr> >, ankerl::unordered_dense::v4_1_0::bucket_type::standard, false>&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::{lambda(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*)#1}::operator()(std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > const&, cista::bitset<512ul> const*) const [clone .isra.0] ()
#2  0x0000000000b372b8 in nigiri::loader::gtfs::load_timetable(nigiri::loader::loader_config const&, cista::strong<unsigned short, nigiri::_source_idx>, nigiri::loader::dir const&, nigiri::timetable&, serializable_table<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx>, cista::hash_all, cista::equals_all, cista::basic_vector<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr, false, unsigned int, cista::allocator<std::pair<cista::bitset<512ul>, cista::strong<unsigned int, nigiri::_bitfield_idx> >, cista::raw::ptr> >, ankerl::unordered_dense::v4_1_0::bucket_type::standard, false>&, nigiri::loader::assistance_times*, nigiri::shapes_storage*) ()
#3  0x0000000000a033a2 in nigiri::loader::load(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nigiri::loader::loader_config>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nigiri::loader::loader_config> > > const&, nigiri::loader::finalize_options const&, nigiri::interval<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400l, 1l> > > > const&, nigiri::loader::assistance_times*, nigiri::shapes_storage*, bool) ()
#4  0x0000000000525520 in motis::import(motis::config const&, std::filesystem::__cxx11::path const&, bool)::{lambda()#11}::operator()() const ()
#5  0x0000000000530084 in motis::task::run(std::filesystem::__cxx11::path const&) ()
#6  0x000000000052ca09 in motis::import(motis::config const&, std::filesystem::__cxx11::path const&, bool) ()
#7  0x0000000000465845 in main ()
```

Data (including config.ini): http://jbb.spline.de/feeds.zip

**Comment by jbruechert** [comment]
It is reproducible with only the de_DELFI.gtfs.zip file included in the collection above.

Better backtrace:.
```
#0  0x0000000000d5f3a1 in std::chrono::operator/<short, std::ratio<60l, 1l>, short, std::ratio<60l, 1l> > (__lhs=std::chrono::duration = { 1439min }, __rhs=std::chrono::duration = { 0min }) at /usr/include/c++/14/bits/chrono.h:772
#1  0x0000000000d5a1a7 in nigiri::loader::gtfs::frequency::number_of_iterations (this=0x1ac66ba0) at /var/home/jonah/kde/src/motis/deps/nigiri/include/nigiri/loader/gtfs/trip.h:42
#2  0x0000000000d57304 in nigiri::loader::gtfs::expand_frequencies<nigiri::loader::gtfs::expand_trip<load_timetable(const nigiri::loader::loader_config&, nigiri::source_idx_t, const nigiri::loader::dir&, nigiri::timetable&, nigiri::hash_map<cista::bitset<512>, cista::strong<unsigned int, nigiri::_bitfield_idx> >&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::<lambda(const std::__cxx11::basic_string<cista::strong<unsigned int, _gtfs_trip_idx> >&, const nigiri::bitfield*)>::<lambda(utc_trip&&)> >(trip_data&, const noon_offset_hours_t&, const nigiri::timetable&, const std::__cxx11::basic_string<cista::strong<unsigned int, _gtfs_trip_idx> >&, const nigiri::bitfield*, const nigiri::interval<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400> > > >&, nigiri::loader::assistance_times*, load_timetable(const nigiri::loader::loader_config&, nigiri::source_idx_t, const nigiri::loader::dir&, nigiri::timetable&, nigiri::hash_map<cista::bitset<512>, cista::strong<unsigned int, nigiri::_bitfield_idx> >&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::<lambda(const std::__cxx11::basic_string<cista::strong<unsigned int, _gtfs_trip_idx> >&, const nigiri::bitfield*)>::<lambda(utc_trip&&)>&&)::<lambda(nigiri::loader::gtfs::frequency_expanded_trip&&)> >(const nigiri::loader::gtfs::trip_data &, const std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > &, const nigiri::bitfield *, struct {...} &&) (trip_data=..., 
    trips="e\x19001596V\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\xff1\000\000\000\000@r\x561c4dbb\000\000\x4dbb1ab0\034V\000\000\000\000\000\000\000\000\000\000E\002FL\000\000\000\000utl::enumerate<std::vector<nigiri::loader::gtfs::frequency, std::allocator<nigiri::loader::gtfs::frequency> > const&, __gnu_cxx::__normal_iterator<n"..., traffic_days=0x1d623d30, consumer=...)
    at /var/home/jonah/kde/src/motis/deps/nigiri/include/nigiri/loader/gtfs/local_to_utc.h:93
#3  0x0000000000d555a5 in nigiri::loader::gtfs::expand_trip<nigiri::loader::gtfs::load_timetable(const nigiri::loader::loader_config&, nigiri::source_idx_t, const nigiri::loader::dir&, nigiri::timetable&, nigiri::hash_map<cista::bitset<512>, cista::strong<unsigned int, nigiri::_bitfield_idx> >&, nigiri::loader::assistance_times*, nigiri::shapes_storage*)::<lambda(const std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >&, const nigiri::bitfield*)>::<lambda(nigiri::loader::gtfs::utc_trip&&)> >(nigiri::loader::gtfs::trip_data &, const nigiri::loader::gtfs::noon_offset_hours_t &, const nigiri::timetable &, const std::__cxx11::basic_string<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx>, std::char_traits<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> >, std::allocator<cista::strong<unsigned int, nigiri::loader::gtfs::_gtfs_trip_idx> > > &, const nigiri::bitfield *, const nigiri::interval<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<int, std::ratio<86400, 1> > > > &, nigiri::loader::assistance_times *, struct {...} &&) (trip_data=..., noon_offsets=..., 
    tt=..., 
    trips="e\x19001596V\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\xff1\000\000\000\000\x4d78ef80\034V\000\000P\x1c4d769eV\000\000\a\020\0002\002", '\000' <repeats 11 times>, "\x4a144ab0\034V\000\000\x49ff11b0\034V\000\000\020\x1c4d78e0V\000\000\x4d78dff0\034V", '\000' <repeats 18 times>, "\001", '\000' <repeats 39 times>, "\001\000\000\000\000\000\000\000\x4cdce9d0\034V", '\000' <repeats 26 times>, "\x4cdb07d0\034V", '\000' <repeats 34 times>..., traffic_days=0x1d623d30, selection=..., assist=0x0, consumer=...) at /var/home/jonah/kde/src/motis/deps/nigiri/include/nigiri/loader/gtfs/local_to_utc.h:337
#4  0x0000000000d52946 in operator() (__closure=0x7ffd1ae069a0, 
    trips="e\x19001596V\000\000\000\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\xff1\000\000\000\000\x4b3784c0\034V\000\000\x4b36b580\034V\000\000\a\020\0002\002", '\000' <repeats 11 times>, "\x4a144ab0\034V\000\000\x49ff11b0\034V\000\000Pu7K\034V\000\0000u7K\034V", '\000' <repeats 18 times>, "\001", '\000' <repeats 39 times>, "\001\000\000\000\000\000\000\000\000[6K\034V", '\000' <repeats 26 times>, "@\x1c4b36b1V", '\000' <repeats 34 times>..., 
    traffic_days=0x1d623d30) at /var/home/jonah/kde/src/motis/deps/nigiri/src/loader/gtfs/load_timetable.cc:182
#5  0x0000000000d53667 in nigiri::loader::gtfs::load_timetable (config=..., src=..., d=..., tt=..., bitfield_indices=..., assistance=0x0, shapes_data=0x6d23540)
    at /var/home/jonah/kde/src/motis/deps/nigiri/src/loader/gtfs/load_timetable.cc:217
#6  0x0000000000d10ff1 in nigiri::loader::gtfs::gtfs_loader::load (this=0x6d2bb60, c=..., src=..., d=..., tt=..., global_bitfield_indices=..., assistance=0x0, shapes_data=0x6d23540)
    at /var/home/jonah/kde/src/motis/deps/nigiri/src/loader/gtfs/loader.cc:19
#7  0x0000000000bbd2ec in nigiri::loader::load (paths=std::vector of length 1, capacity 1 = {...}, finalize_opt=..., date_range=..., a=0x0, shapes=0x6d23540, ignore=true)
    at /var/home/jonah/kde/src/motis/deps/nigiri/src/loader/load.cc:52
#8  0x0000000000552bb1 in operator() (__closure=0x6d214e0) at /var/home/jonah/kde/src/motis/src/import.cc:261
#9  0x000000000055c9a4 in std::__invoke_impl<void, motis::import(const config&, const std::filesystem::__cxx11::path&, bool)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/14/bits/invoke.h:61
#10 0x000000000055a8c1 in std::__invoke_r<void, motis::import(const config&, const std::filesystem::__cxx11::path&, bool)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/14/bits/invoke.h:111
#11 0x00000000005588c3 in std::_Function_handler<void(), motis::import(const config&, const std::filesystem::__cxx11::path&, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/14/bits/std_function.h:290
#12 0x00000000005619c6 in std::function<void()>::operator() (this=0x6d290f0) at /usr/include/c++/14/bits/std_function.h:591
#13 0x0000000000560bd4 in motis::task::run (this=0x6d29090, data_path=filesystem::path "data") at /var/home/jonah/kde/src/motis/src/import.cc:83
#14 0x00000000005561ce in motis::import (c=..., data_path=filesystem::path "data", write=true) at /var/home/jonah/kde/src/motis/src/import.cc:469
#15 0x0000000000404449 in main (ac=3, av=0x7ffd1ae0cde0) at /var/home/jonah/kde/src/motis/exe/main.cc:119
```
